FROM fluent/fluentd:v1.11-1

ENV FLUENT_UID=0
USER root
RUN mkdir /buffer
RUN ["gem", "install", "fluent-plugin-kafka", "--no-document", "--version", "0.7.9"]
RUN ["gem", "install", "fluent-plugin-concat", "--no-document", "--version", "2.4.0"]
RUN ["gem", "install", "fluent-plugin-record-modifier", "--no-document", "--version", "2.1.0"]
RUN ["gem", "install", "fluent-plugin-grok-parser", "--no-document", "--version", "2.6.2"]
RUN ["gem", "install", "fluent-plugin-detect-exceptions", "--no-document", "--version", "0.0.13"]
RUN ["gem", "install", "fluent-plugin-route", "--no-document", "--version", "1.0.0"]
